import { Category, Order, Product } from './models';
export const CATEGORIES: Category[] = [
 ['Smart Tech','⌁',148,'#dbeafe'],['Fashion','◈',326,'#fce7f3'],['Home & Living','⌂',214,'#dcfce7'],['Beauty','✦',107,'#fef3c7'],['Sports','◎',89,'#ede9fe'],['Audio','♫',73,'#cffafe'],['Gaming','⌘',94,'#fee2e2'],['Cameras','◉',62,'#e0e7ff'],['Books','▤',430,'#ffedd5'],['Watches','◷',81,'#ccfbf1'],['Groceries','♧',298,'#ecfccb'],['Automotive','◇',115,'#f1f5f9'],['Kids','★',173,'#fae8ff'],['Travel','✈',55,'#dbeafe'],['Furniture','▰',96,'#fef9c3'],['Footwear','◒',151,'#ffe4e6'],['Jewelry','♢',78,'#fef3c7'],['Office','▣',132,'#e0f2fe'],['Outdoors','♨',67,'#dcfce7'],['Wellness','♡',121,'#fce7f3']
].map(([name,icon,count,color])=>({name:String(name),icon:String(icon),count:Number(count),color:String(color)}));
const names=['AirPulse Pro Headphones','NovaFit Smart Watch','Lumina Desk Light','AeroRun Cloud Sneakers','Terra Ceramic Set','PixelPod Mini Speaker','Urban Carry Backpack','PureBlend Mixer','VisionX Action Camera','CloudSoft Lounge Chair','Aura Skincare Ritual','Orbit Mechanical Keyboard','Vela Linen Shirt','CoreFlex Yoga Mat','SonicBuds Air','BrewCraft Coffee Maker','Trailmark Bottle','Halo Smart Lamp','Frame Classic Watch','Mellow Knit Throw'];
const brands=['Nexa','Lumio','Aster & Co.','Verve','Kanso','Orbit','Northstar','Mira'];
export const PRODUCTS: Product[] = Array.from({length:100},(_,i)=>({id:i+1,name:names[i%names.length],brand:brands[i%brands.length],category:CATEGORIES[i%CATEGORIES.length].name,price:Math.round(39+(i*37)%570)+.99,oldPrice:Math.round(75+(i*49)%700)+.99,rating:3.8+(i%12)/10,reviews:38+(i*71)%2200,image:`https://picsum.photos/seed/marketflow-${i+11}/640/640`,badge:i%8===0?'Best seller':i%7===0?'New':undefined,stock:i%9===0?0:8+(i%40),description:'Thoughtfully designed with premium materials, effortless performance, and a modern aesthetic made for everyday life.',features:['Premium build quality','One-year warranty','Fast, free delivery','30-day easy returns']}));
export const ORDERS: Order[] = Array.from({length:100},(_,i)=>({id:`MF-${80420+i}`,customer:`Customer ${i+1}`,total:Math.round(64+(i*83)%1900)+.98,status:['Delivered','Processing','Shipped','Cancelled'][i%4],date:new Date(2026,6-(i%6),28-(i%25)).toISOString(),items:1+i%5}));
export const CUSTOMERS = Array.from({length:50},(_,i)=>({id:i+1,name:`MarketFlow Customer ${i+1}`,email:`customer${i+1}@example.com`,orders:1+i%12,spent:120+(i*97)%5200}));
